---
# tasks file for omero-prometheus-exporter

- name: omero prometheus exporter | install virtualenv package
  become: yes
  yum:
    name: python-virtualenv
    state: present

- name: omero prometheus exporter | create system user
  become: yes
  user:
    name: "{{ omero_prometheus_exporter_system_user }}"
    state: present
    system: yes

- name: omero prometheus exporter | install omero-prometheus-tools
  become: yes
  pip:
    name: omero-prometheus-tools
    version: "{{ omero_prometheus_tools_version }}"
    state: present
    virtualenv: /opt/prometheus-omero-tools
    virtualenv_site_packages: yes
  notify:
  - restart prometheus-omero-exporter

- name: omero prometheus exporter | configure service
  become: yes
  template:
    dest: /etc/sysconfig/prometheus-omero-exporter
    src: sysconfig-prometheus-omero-exporter.j2
    owner: "{{ omero_prometheus_exporter_system_user }}"
    group: root
    mode: 0440
  notify:
  - restart prometheus-omero-exporter

- name: omero prometheus exporter | install service
  become: yes
  template:
    dest: /etc/systemd/system/prometheus-omero-exporter.service
    src: systemd-prometheus-omero-exporter-service.j2
  notify:
  - restart prometheus-omero-exporter

- name: omero prometheus exporter | enable service
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: prometheus-omero-exporter
    state: started
