---
# tasks file for omero-prometheus-exporter

# TODO: Move to a separate role?
- name: omero prometheus exporter | install python3
  become: true
  yum:
    name: python36
    state: present

- name: omero web | install python3
  become: true
  apt:
    name:
      - python3.6
      - python3.6-distutils
      - python3.6-venv
    state: present
  when: ansible_os_family == 'Debian'

- name: omero prometheus exporter | create system user
  become: yes
  user:
    name: "{{ omero_prometheus_exporter_system_user }}"
    state: present
    system: yes

- name: omero prometheus exporter | install omero-prometheus-tools
  become: yes
  pip:
    name: "{{ omero_prometheus_tools_requirements }}"
    state: present
    virtualenv: /opt/prometheus-omero-tools/venv3
    virtualenv_command: /usr/bin/python3 -mvenv
  notify:
  - restart prometheus-omero-exporter

- name: omero prometheus exporter | configure service
  become: yes
  template:
    dest: /etc/sysconfig/prometheus-omero-exporter
    src: sysconfig-prometheus-omero-exporter.j2
    owner: "{{ omero_prometheus_exporter_system_user }}"
    group: root
    mode: 0440
  notify:
  - restart prometheus-omero-exporter

- name: omero prometheus exporter | install service
  become: yes
  template:
    dest: /etc/systemd/system/prometheus-omero-exporter.service
    src: systemd-prometheus-omero-exporter-service.j2
  notify:
  - restart prometheus-omero-exporter

- name: omero prometheus exporter | enable service
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: prometheus-omero-exporter
    state: started
