---
# handlers file for omero-prometheus-exporter

- name: restart prometheus-omero-sessions
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: prometheus-omero-sessions
    state: restarted

- name: restart prometheus-omero-counts
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: prometheus-omero-counts
    state: restarted
