---
# handlers file for omero-prometheus-exporter

- name: restart prometheus-omero-exporter
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: prometheus-omero-exporter
    state: restarted
