---
- name: Converge
  hosts: all
  roles:

    - role: ome.postgresql
      postgresql_install_server: true
      postgresql_databases:
        - name: omero
      postgresql_users:
        - user: omero
          password: omero
          databases: [omero]

    - role: ome.omero_server

    - role: ome.omero_prometheus_exporter
      omero_prometheus_exporter_omero_user: root
      omero_prometheus_exporter_omero_password: omero

  vars:
    postgresql_version: "10"
